# Generated by Django 5.1.6 on 2025-03-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('soil_type', models.CharField(max_length=100)),
                ('water_needed', models.FloatField()),
                ('expected_yield', models.FloatField()),
                ('cost', models.FloatField()),
            ],
        ),
    ]
